import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar.jsx'
import Footer from './components/footer.jsx'

import style from './page.module.css'
import movie from './components/css/movie.module.css'
import styleid from './movies/[id]/id.module.css'

import NextNProgress from 'nextjs-progressbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.ClassName}>
      <NextNProgress color="blue" height={4} />
        <Navbar/>
        <main className={style.body}>
          {children}
        </main>
        
        <Footer/>
        </body>
    </html>
  )
}
